# Generated by Django 3.0 on 2019-12-18 15:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalusersdata',
            name='first_name',
            field=models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='personalusersdata',
            name='last_name',
            field=models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='personalusersdata',
            name='nick',
            field=models.CharField(error_messages={'unique': 'A user with that nick already exists.'}, max_length=120, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='nick'),
        ),
    ]
